ALTER TABLE `users` ADD `customer_id` VARCHAR(255) NULL AFTER `activation`;
ALTER TABLE `users` ADD `plan_switched` ENUM('DOWNGRADE','UPGRADE','CANCEL_DOWNGRADE','CANCEL_UPGRADE') NULL DEFAULT NULL AFTER `customer_id`;
ALTER TABLE `users` CHANGE `plan_switched` `plan_switched` ENUM('DOWNGRADE','UPGRADE','CANCEL_DOWNGRADE','CANCEL_UPGRADE','CANCELLED') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `plan_switched` `plan_switched` ENUM('DOWNGRADE','UPGRADE','CANCELLED') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `plan_switched` `plan_switched` ENUM('DOWNGRADE','UPGRADE','CANCELLED','CANCELLED_DOWNGRADE') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
